image: mhart/alpine-node:10

babel:
  stage: build
  tags: ['docker']
  script:
    - yarn install
    - yarn build
  artifacts:
    paths:
      - node_modules/
      - lib/
  expire_in: 1 week

formatting:
  stage: test
  tags: ['docker']
  script: yarn test-format

holidays:
  stage: test
  tags: ['docker']
  script: yarn test-holidays

