image: alpine:3.7
stages:
    - prepare
    - build
    - test

prepare:
  stage: prepare
  tags: ['docker']
  script:
    - apk add --no-cache nodejs nodejs-npm
    - node --version
    - npm --version
    - npm install --global yarn
    - yarn --version

babel:
  stage: build
  tags: ['docker']
  script:
    - yarn install
    - yarn build

formatting:
  stage: test
  tags: ['docker']
  script: yarn test-format

holidays:
  stage: test
  tags: ['docker']
  script: yarn test-holidays

