image: mhart/alpine-node:8

before_script:
  - alias gulp='$(yarn bin)/gulp'

build:
  stage: build
  tags: ['docker']
  script:
    - yarn install
    - gulp build
  artifacts:
    paths:
      - node_modules/
      - lib/
    expire_in: 1 week

test-formatting:
  stage: test
  tags: ['docker']
  script: gulp test-format

test-holidays:
  stage: test
  tags: ['docker']
  script: gulp test-holidays

