image: alpine:3.7
before_script:
  - apk add --no-cache nodejs nodejs-npm
  - node --version
  - npm --version
  - npm install --global yarn
  - yarn --version
  - yarn install

babel:
  stage: build
  tags: ['docker']
  script: yarn build

formatting:
  stage: test
  tags: ['docker']
  script: yarn test-format

holidays:
  stage: test
  tags: ['docker']
  script: yarn test-holidays

